name: flutter_application_p3l
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^7.1.1
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.4
  font_awesome_flutter: ^10.0.0
  animated_splash_screen: ^1.3.0
  lottie: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  shared_preferences: ^2.0.6
  intl: ^0.19.0
  provider: ^6.0.0
  table_calendar: ^3.0.9
  carousel_slider: ^5.0.0
  numberpicker: ^2.1.2
  http: ^1.2.2
  flutter_riverpod: ^2.6.1
  pdf: ^3.6.0
  printing: ^5.4.0
  flutter_dotenv: ^5.0.2
  decimal: ^2.0.0
  flutter_secure_storage: ^9.2.4
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^19.2.1
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo.png